[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/features"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/:id"
  to = "https://shurl.hasanarif.com/:id "
  status = 200


